name: "$(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)"
trigger:
  branches:
    include:
      - trunk
      - feature/*
  paths:
    include:
      - ComponentNameType/*
resources:
  - repo: self
    clean: "true"
    fetchDepth: "1"
    
variables:
  pythonVersion: '3.13'
  component-name: ComponentNameType
  project-name: plataforma-ia
  

stages:
  - stage: Build
    displayName: Build and Publish
    jobs:
      - job: Linux
        displayName: Build and publication of artifact
        pool:      
          name: Build
          demands: 
            - Agent.OS -equals Linux
        steps:
          - template: /ComponentNameType/deployment/pipelines/build.yml
          - template: /ComponentNameType/deployment/pipelines/deploy.yml
          