name: CD - Deployment

on:
  push:
    branches: [main, trunk]

jobs:
  deploy:
    name: Despliegue en mi computadora
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Levantar Stack con Docker Compose
        run: |
          # Usamos -f para apuntar al archivo que está dentro de la carpeta deployment
          docker-compose -f deployment/docker-compose.yml up -d --build
          
      - name: Verificar Contenedores
        run: docker ps
