name: CD - Deployment

on:
  push:
    branches: [main, trunk]

jobs:
  deploy:
    name: Despliegue en mi computadora
    runs-on: self-hosted  # <--- Esto le dice que use tu PC, no la nube
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Levantar Stack con Docker Compose
        run: |
          # Esto construye la API y levanta MLflow localmente
          docker-compose up -d --build
          
      - name: Verificar Contenedores
        run: docker ps
